In [1]:
#Lets start by printing hello world

Hello = "Hello World"

In [3]:
print("start: " + Hello)

start: Hello World


In [4]:
#lets import numpy
#In deep learning we use vectors and matrices
#so its best to perform with numpy, so it cn help to return the same values
import numpy as np

firstArray = np.array([1, 2, 3])
print (firstArray + 3)

#You will see why we use numpy and not math

[4 5 6]


In [5]:
#A sigmoid function sigmoid(x) can be calculated as s =  1/(1 + np.exp(-x))
#Note we use np.exp(-x) and not math.exp(-x) because x will be a vector 
#math.exp(-x) will give an error whena vector is passed to it


def sigmoid(x):
    s =  1/(1 + np.exp(-x))
    return s



In [6]:
testX = np.array([1, 2, 3])
print("sigmoid(testX) = " + str(sigmoid(testX)))

sigmoid(testX) = [0.73105858 0.88079708 0.95257413]


In [7]:
#To computegradients to optimixe lossfunction using backpropagation - sigmoid(x) * (1 - sigmoid(x))
def sigmoidDerivative(x):
    s = sigmoid(x)
    sd = s * (1 - s)
    
    return sd

In [8]:
testX = np.array([1, 2, 3])
print ("sigmoidDerivative(testX) = " + str(sigmoidDerivative(testX)))

sigmoidDerivative(testX) = [0.19661193 0.10499359 0.04517666]


In [9]:
#Images ussually come in RGB format hence an image can come in a size (length,height,3)
#The 3 is the number of channels Red(R), Green(G), and Blue(B) 
#When you read the image as the input of an algorithm - maybe to perform an operation
#You convert/reshape it to a 1D vector (that is you unroll it) 
# so to unroll into a 1d vector you do theImage.reshape(height*width*3,1)
#to get any of the dimension you do theImage.shape[column] - for length: theImage.shape[0]

#you cna also reshape to one column using -1 - image.reshape(-1,1)
def reshapeImage(image):
    #imageVector = image.reshape(-1,1)
    imageVector = image.reshape(image.shape[0] * image.shape[1] * image.shape[2],1)
    # YOUR CODE ENDS HERE
    
    return imageVector

In [10]:
testImage = np.array([[[ 0.778,  0.344],
                     [ 0.779,  0.618],
                     [ 0.533 ,  0.340]],

                   [[ 0.999,  0.944],
                    [ 0.890,  0.652],
                    [ 0.211,  0.222]],

                   [[ 0.587,  0.023],
                    [ 0.096,  0.346],
                    [ 0.543,  0.879]]])

print ("reshapeImage(image) = " + str(reshapeImage(testImage)))


reshapeImage(image) = [[0.778]
 [0.344]
 [0.779]
 [0.618]
 [0.533]
 [0.34 ]
 [0.999]
 [0.944]
 [0.89 ]
 [0.652]
 [0.211]
 [0.222]
 [0.587]
 [0.023]
 [0.096]
 [0.346]
 [0.543]
 [0.879]]


In [11]:
#You can normalize a matrix by using np.linalg.norm 
#ord set the order 2 means 2-norm, axis - 1 for row and 0 for columnwise
#note: do not use /= because we want to broadcasting
def normalizeX(x):
    x_norm = np.linalg.norm(x,ord = 2, axis = 1, keepdims=True)
    x = x/x_norm
    return x

In [13]:
x = np.array([[0, 2, 3],
              [1, 5, 3]])
print("normalizeX(x) = " + str(normalizeX(x)))

normalizeX(x) = [[0.         0.5547002  0.83205029]
 [0.16903085 0.84515425 0.50709255]]


In [14]:
#Softmax
def softmax(x):
    x_exp = np.exp(x)
    
    x_sum = np.sum(x_exp,axis=1,keepdims=True)
    
    s = x_exp / x_sum
   
    return s

In [15]:
testX = np.array([[9, 3, 4, 0, 0],
                [9, 3, 0, 0 ,0]])
print("softmax(x) = " + str(softmax(testX)))

softmax(x) = [[9.90625200e-01 2.45551437e-03 6.67478009e-03 1.22252862e-04
  1.22252862e-04]
 [9.97159112e-01 2.47171032e-03 1.23059211e-04 1.23059211e-04
  1.23059211e-04]]


In [16]:
#VECTORIZATION
x1 = [7, 3, 4, 1, 0, 3, 1, 0, 0, 0, 5, 6, 4, 0, 1]
x2 = [8, 3, 1, 8, 0, 2, 1, 2, 0, 0, 5, 8, 7, 0, 3]


dot = np.dot(x1,x2)
print ("dot = " + str(dot))

outer = np.outer(x1,x2)
print ("outer = " + str(outer))

mul = np.multiply(x1,x2)
print ("elementwise multiplication = " + str(mul))

dot = 188
outer = [[56 21  7 56  0 14  7 14  0  0 35 56 49  0 21]
 [24  9  3 24  0  6  3  6  0  0 15 24 21  0  9]
 [32 12  4 32  0  8  4  8  0  0 20 32 28  0 12]
 [ 8  3  1  8  0  2  1  2  0  0  5  8  7  0  3]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [24  9  3 24  0  6  3  6  0  0 15 24 21  0  9]
 [ 8  3  1  8  0  2  1  2  0  0  5  8  7  0  3]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [40 15  5 40  0 10  5 10  0  0 25 40 35  0 15]
 [48 18  6 48  0 12  6 12  0  0 30 48 42  0 18]
 [32 12  4 32  0  8  4  8  0  0 20 32 28  0 12]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 8  3  1  8  0  2  1  2  0  0  5  8  7  0  3]]
elementwise multiplication = [56  9  4  8  0  6  1  0  0  0 25 48 28  0  3]


In [18]:
#To evaluate thepreformance of yourmodel and know how differnt your predictions are,
#you can use L1 or L2 lss functions
def L1(yhat, y):
    loss = np.sum(abs(y-yhat))
    return loss

In [19]:
yhat = np.array([.8, 0.6, 0.1, .8, .7])
y = np.array([1, 0, 0, 1, 1])
print("L1 = " + str(L1(yhat, y)))


L1 = 1.4


In [20]:
def L2(yhat, y):
    ydifference= y - yhat
    loss = np.sum(np.dot(ydifference,ydifference))
    
    return loss

In [22]:
yhat = np.array([.8, 0.6, 0.1, .8, .7])
y = np.array([1, 0, 0, 1, 1])

print("L2 = " + str(L2(yhat, y)))


L2 = 0.5399999999999999
